//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SfStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHangBan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonHangBan()
        {
            this.DonHangBanCts = new HashSet<DonHangBanCt>();
        }
    
        public long Id { get; set; }
        public string SoDh { get; set; }
        public Nullable<long> KhId { get; set; }
        public Nullable<System.DateTime> NgayBan { get; set; }
        public string DiaChi { get; set; }
        public string Tinh { get; set; }
        public string Huyen { get; set; }
        public string GhiChu { get; set; }
        public Nullable<decimal> TongSL { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public Nullable<decimal> TongCk { get; set; }
        public Nullable<decimal> PhiVc { get; set; }
        public Nullable<decimal> TongTt { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Date0 { get; set; }
        public Nullable<System.TimeSpan> Time0 { get; set; }
        public Nullable<long> UserId0 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.TimeSpan> Time2 { get; set; }
        public Nullable<long> UserId2 { get; set; }
        public bool giohang_yn { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangBanCt> DonHangBanCts { get; set; }
    }
}
