//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SfStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DotKmCt
    {
        public string MaDotkm { get; set; }
        public System.DateTime NgayBd { get; set; }
        public System.DateTime NgayKt { get; set; }
        public long ChietKhauId { get; set; }
        public long LoaiSpId { get; set; }
    
        public virtual ChietKhau ChietKhau { get; set; }
        public virtual DotKm DotKm { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
