//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SfStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GioHang
    {
        public long UserId { get; set; }
        public long SanPhamId { get; set; }
        public Nullable<decimal> SoLuong { get; set; }
        public Nullable<System.DateTime> Date0 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
    
        public virtual SanPham SanPham { get; set; }
        public virtual User User { get; set; }
    }
}
