//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SfStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DonHangBans = new HashSet<DonHangBan>();
        }
    
        public long Id { get; set; }
        public string HoTen { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public Nullable<int> GioiTinh { get; set; }
        public string GhiChu { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Date0 { get; set; }
        public Nullable<System.TimeSpan> Time0 { get; set; }
        public Nullable<long> UserId0 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.TimeSpan> Time2 { get; set; }
        public Nullable<long> UserId2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangBan> DonHangBans { get; set; }
    }
}
