//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SfStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KichCo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KichCo()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public long Id { get; set; }
        public string Size { get; set; }
        public Nullable<System.DateTime> Date0 { get; set; }
        public Nullable<System.TimeSpan> Time0 { get; set; }
        public Nullable<long> UserId0 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.TimeSpan> Time2 { get; set; }
        public Nullable<long> UserId2 { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
