//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SfStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public long NhomId { get; set; }
        public string MenuId { get; set; }
        public bool Xem { get; set; }
        public bool Them { get; set; }
        public bool Sua { get; set; }
        public bool Xoa { get; set; }
    
        public virtual MenuAdmin MenuAdmin { get; set; }
        public virtual NhomNguoiDung NhomNguoiDung { get; set; }
    }
}
