//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SfStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DonHangBanCts = new HashSet<DonHangBanCt>();
            this.GioHangs = new HashSet<GioHang>();
            this.NhapKhoCts = new HashSet<NhapKhoCt>();
        }
    
        public long Id { get; set; }
        public string MaSp { get; set; }
        public string TenSp { get; set; }
        public string ImageName { get; set; }
        public string MoTa { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<decimal> GiaVon { get; set; }
        public Nullable<decimal> GiaBan { get; set; }
        public Nullable<long> LoaiSpId { get; set; }
        public Nullable<long> NccId { get; set; }
        public bool ChoPhepBanAm { get; set; }
        public bool SpMoi { get; set; }
        public bool SpNoiBat { get; set; }
        public bool SpSale { get; set; }
        public Nullable<long> SizeId { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> Date0 { get; set; }
        public Nullable<System.TimeSpan> Time0 { get; set; }
        public Nullable<long> UserId0 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.TimeSpan> Time2 { get; set; }
        public Nullable<long> UserId2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHangBanCt> DonHangBanCts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual KichCo KichCo { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhapKhoCt> NhapKhoCts { get; set; }
    }
}
