//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SfStoreOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThietLapChung
    {
        public long Id { get; set; }
        public string Logo { get; set; }
        public string TenCuaHang { get; set; }
        public string TenVietTat { get; set; }
        public string DiaChi { get; set; }
        public string Sdt { get; set; }
        public string Email { get; set; }
        public string GioiThieu { get; set; }
        public string SliderAnh1 { get; set; }
        public string SliderTieuDe1 { get; set; }
        public string SliderMoTa1 { get; set; }
        public string SliderLink1 { get; set; }
        public string SliderAnh2 { get; set; }
        public string SliderTieuDe2 { get; set; }
        public string SliderMoTa2 { get; set; }
        public string SliderLink2 { get; set; }
        public string SliderAnh3 { get; set; }
        public string SliderTieuDe3 { get; set; }
        public string SliderMoTa3 { get; set; }
        public string SliderLink3 { get; set; }
        public Nullable<long> LoaiSpId1 { get; set; }
        public Nullable<long> LoaiSpId2 { get; set; }
        public Nullable<long> LoaiSpId3 { get; set; }
        public string TieuDeKm { get; set; }
        public string MoTaKm { get; set; }
        public Nullable<long> UserId0 { get; set; }
        public Nullable<System.DateTime> Date0 { get; set; }
        public Nullable<System.TimeSpan> Time0 { get; set; }
        public Nullable<long> UserId2 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.TimeSpan> Time2 { get; set; }
        public Nullable<long> LoaiSpId4 { get; set; }
        public Nullable<long> LoaiSpId5 { get; set; }
        public Nullable<long> LoaiSpId6 { get; set; }
    }
}
